### ISSUE TITLE
Autocleaning needs to have power option exposed during setup_autoclean_protocol

### ISSUE THREAD

**Issue by Antonedw** [machineagency/sonication_station#13]
Expose power option as an input when using **prompt mode**  else leads to error due to missing argument when running protocol.

**Comment by Poofjunior** [comment]
also implemented in this branch. Needs testing.
https://github.com/machineagency/sonication_station/tree/dev/duty_cycle_sonication

**Comment by Poofjunior** [comment]
Ok this looks good!
