### ISSUE TITLE
Sonication horn remains on after KeyboardInterrupt in Prompt Mode

### ISSUE THREAD

**Issue by Antonedw** [machineagency/sonication_station#14]
When interrupting a protocol running in prompt mode the sonication horn stays on after the keyboard interruption. The horn stays on to the same setting that was present during the keyboard interruption. Currently, the only way to stop the horn is to turn the entire machine on and off completely.

**Comment by Poofjunior** [comment]
Ok; this looks like it should be a quick fix. Changes are up here in a branch that I should be able to test before the end of the weekend.
https://github.com/machineagency/sonication_station/tree/dev/sonicator_safe_exit

**Comment by Poofjunior** [comment]
Ok this should now be fixed.
