### ISSUE TITLE
Duty cycle for sonication horn not present

### ISSUE THREAD

**Issue by Antonedw** [machineagency/sonication_station#15]
The option of the duty cycle is not present as an argument to sonicate_well(). At the moment, a duty (ratio on/off) cycle is achievable by just calling the horn to run in another well, however, the power option to zero or a pause feature is needed.

**Comment by Poofjunior** [comment]
Ok, also implemented, but needs to get tested later.
https://github.com/machineagency/sonication_station/tree/dev/duty_cycle_sonication

**Comment by Poofjunior** [comment]
Ok, this is now implemented. When you run it, you'll get a print message when the sonicator turns on and off. (We can get rid of this if you want.)
```
>>> sonicate_well 0 A 0 15 2.5 1 1 2 autoclean=False
Moving to: (264.055, 200.000)
Sonicating for 2.5 seconds!!
0.00 | Sonicator on.
2.00 | Sonicator off.
2.00 | Sonicator on.
2.50 | Sonicator off.
2.50 | Finished sonicating.
done!
Moving to: (124.250, 79.750)
Sonicating for 3.0 seconds!!
0.00 | Sonicator on.
0.50 | Sonicator off.
1.00 | Sonicator on.
1.50 | Sonicator off.
2.00 | Sonicator on.
2.50 | Sonicator off.
3.00 | Finished sonicating.
done!
Moving to: (96.167, 79.750)
Sonicating for 3.0 seconds!!
0.00 | Sonicator on.
0.50 | Sonicator off.
1.00 | Sonicator on.
1.50 | Sonicator off.
2.00 | Sonicator on.
2.50 | Sonicator off.
3.00 | Finished sonicating.
done!
```
